version: '3'

services:
  piter_bot:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - app  
    volumes:
      - ./config/db:/usr/src/app/config/db
 
  mariabd:
    image: mariadb
    restart: always
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=piter
      - MARIADB_USER=piter
      - MARIADB_PASSWORD=piter
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - app  
    expose:
      - 3306
